#!/bin/sh

echo "\nRunning JS Beautify\n"

BASEDIR=$(git rev-parse --show-toplevel)

files=$(git diff --cached --name-only --diff-filter=ACM | grep '.js$')

for file in $files; do
  js-beautify -rn "${BASEDIR}/${file}"
  git add "${BASEDIR}/${file}"
done


echo "/nValidating js with JS Hint before commit/n"

files=$(git diff --cached --name-only --diff-filter=ACMR -- *.js **/*.js)
pass=true


if [ "$files" != "" ]; then
    for file in ${files}; do
        result=$(jshint ${file})

        if [ "$result" != "" ]; then
            echo "$result"
            echo "\n"
            pass=false
        fi
    done
fi


if $pass; then
    exit 0
else
    echo ""
    echo "COMMIT FAILED:"
    echo "Some JavaScript files are invalid. Please fix errors and try committing again."
    exit 1
fi
