#!/usr/bin/env bash


sudo service cassandra stop
cd /var/log/cassandra
sudo rm -rf *
cd /var/lib/cassandra
sudo rm -rf *
cd $GOHOME/src/github.com/Novetta/VideoEnterprise/videx2/dev
rm executor.cfg
sudo service cassandra start
sleep 15
echo "Waiting for cassandra to start...."
bash bootstrap.sh

